# Generated by Django 4.0.6 on 2022-07-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('Papatoetoe', 'Papatoetoe'), ('Onehunga', 'Onehunga')], max_length=200, null=True),
        ),
    ]
