# Generated by Django 4.0.5 on 2022-07-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-created_date',)},
        ),
    ]
