# Generated by Django 5.0.2 on 2024-02-20 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='photos/services')),
                ('service_type', models.CharField(choices=[('startprice', 'Starting Price'), ('colourservice', 'Colour Services'), ('lighteningservice', 'Lightening Services'), ('kerat', 'Keratin Straight Permanent'), ('treatment', 'Treatment'), ('styling', 'Styling'), ('extension', 'Extension')], max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
