# Generated by Django 4.0.5 on 2022-07-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to='static/photos/%Y/%m/%d/'),
        ),
    ]
