# Generated by Django 4.0.5 on 2022-07-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(upload_to='static/services/'),
        ),
    ]
