# Generated by Django 4.0.5 on 2022-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('startprice', 'Starting Price'), ('colourservice', 'Colour Services'), ('lighteningservice', 'Lightening Services'), ('kerat', 'Keratin Straight Permanent'), ('treatment', 'Treatment')], max_length=200, null=True),
        ),
    ]
