# Generated by Django 5.0.2 on 2024-02-20 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.site')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField()),
                ('stylist_name', models.CharField(blank=True, choices=[('No Prefered', 'No Prefered'), ('Arnie', 'Arnie'), ('Dana', 'Dana'), ('Purvi Alison', 'Purvi Alison'), ('Ailyn', 'Ailyn'), ('Mary', 'Mary'), ('Alison', 'Alison')], max_length=200, null=True)),
                ('location', models.CharField(choices=[('1', 'Onehunga'), ('2', 'Papatoetoe')], max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('date_chosen', models.DateField(null=True)),
                ('time_chosen', models.TimeField(null=True)),
                ('services', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.site')),
            ],
            options={
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.booking')),
            ],
        ),
    ]
