# Generated by Django 4.0.5 on 2022-07-02 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=20)),
                ('location', models.CharField(choices=[('Papatoetoe', 'Papatoetoe'), ('Onehunga', 'Onehunga')], max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('date_chosen', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'unique_together': {('name', 'phone')},
            },
        ),
    ]
