# Generated by Django 4.0.5 on 2022-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_chosen',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_chosen',
            field=models.DateField(null=True),
        ),
    ]
