# Generated by Django 4.0.6 on 2022-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_services_booking_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stylist_name',
            field=models.CharField(blank=True, choices=[('No Prefered', 'No Prefered'), ('Arnie', 'Arnie'), ('Dana', 'Dana'), ('Purvi Alison', 'Purvi Alison'), ('Ailyn', 'Ailyn'), ('Mary', 'Mary'), ('Alison', 'Alison')], max_length=200, null=True),
        ),
    ]
