# Generated by Django 4.0.6 on 2022-07-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_site_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('1', 'Onehung'), ('2', 'Papatoetoe')], max_length=200),
        ),
    ]
