# Generated by Django 4.0.5 on 2023-07-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.site'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('1', 'Onehunga'), ('2', 'Papatoetoe')], max_length=200),
        ),
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.booking')),
            ],
        ),
    ]
