# Generated by Django 4.0.6 on 2022-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('Papatoetoe', 'Papatoetoe'), ('Onehunga', 'Onehunga')], max_length=200),
        ),
    ]
