# Generated by Django 4.0.6 on 2022-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('1', 'Onehunga'), ('2', 'Papatoetoe')], max_length=200),
        ),
    ]
