# Generated by Django 4.0.6 on 2022-07-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.booking')),
            ],
        ),
    ]
